#!/bin/sh

# This is a basic script to checkout the mplayer source from svn and set things
# up for building source and binary packages. This includes creating the
# debian/changelog file and replacing mplayer's debian directory with our own.
#
# It also updates existing svn source if it's already been checked out.
#
# Currently this is very simple and probably won't handle errors very well.

set -e

url='svn://svn.mplayerhq.hu/mplayer/trunk'

path_rev() {
    path=$1
    [ $path ] || path=.

    svn info $path | sed 's/^Revision:\s\+\([0-9]\+\).*/\1/p;d'
}

external_revs() {
    svn propget svn:externals | cut -f 1 | \
    while read external; do
        [ $external ] || break

        echo $external: $(path_rev $external)
    done
}

# Restore original svn source
./source original

cd mplayer-trunk

if [ -d debian ]; then
    # Looks like we already have the source, so do an update.
    svn update
else
    svn checkout $url .
fi

# Generate a changelog from the template in debian_new/changelog.template.
CHANGELOG="debian_new/changelog"
[ -e "$CHANGELOG" ] && mv "$CHANGELOG" "${CHANGELOG}.prev"
rev=$(path_rev)
date=$(date -R)
externals=$(external_revs | sed 's/.*/    - &/' | sed -n '1{h;d};H;${g;s/\n/\\n/gp}')
sed "s/#SVN_REV#/$rev/;s/#DATE#/$date/;s/#EXTERNAL_REVS#/$externals/" \
  "${CHANGELOG}.template" > "$CHANGELOG"

cd ..

# Replace mplayer's debian directory with ours.
./source modified
